
target 'CocoaPodsTest' do
  platform :ios, '13.0'

  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPodsTest
  pod 'honeycomb-opentelemetry-swift', :path => '../../'

  target 'CocoaPodsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CocoaPodsTestUITests' do
    # Pods for testing
  end

end
